using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;

public static class ResolutionPresetTests {
 static int checks;
 static void Assert(bool value,string text){checks++;if(!value)throw new Exception("Resolution check failed: "+text);}
 static void Reject(Action action,string text){bool rejected=false;try{action();}catch{rejected=true;}Assert(rejected,text);}
 static Game Fixture(string root,string name){string folder=Path.Combine(root,name);Directory.CreateDirectory(folder);var g=new Game{Name=name,Root=folder,Exe=Path.Combine(folder,"test-game.exe")};File.WriteAllBytes(g.Exe,new byte[128]);return g;}
 static readonly string BridgeIni="[amd-nr]\nScale=0.25\nStartOn=0\nPasses=2\nInline=1\nAsync=0\n[Other]\nScale=0.9\n";
 static readonly string UpscaleIni="[UpscaleRatio]\nUpscaleRatioOverrideEnabled=auto\nUpscaleRatioOverrideValue=auto\n[QualityOverrides]\nQualityRatioOverrideEnabled=true\n[DlssNr]\nAmdModelScale=0.75\nPasses=2\n[FrameGen]\nEnabled=false\n";
 static void Install(Game g,string root,string ini,bool bridge){string source=Path.Combine(root,Guid.NewGuid().ToString("N")+".ini");File.WriteAllText(source,ini);string component=Path.Combine(root,Guid.NewGuid().ToString("N")+".bin");File.WriteAllText(component,"known fixture component");StackEngine.ApplyPrepared(g,new StackProfile{Input=bridge?"reshade32":"dlssg",Neural=true},new Dictionary<string,string>{{bridge?"amd-nr.ini":"OptiScaler.ini",source},{"fixture-component.bin",component}},s=>{});}
 public static void Run(){
  Program.Testing=true;string root=Path.Combine(Core.Data,"test-fixtures","resolution-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);string store=ResolutionPresets.StorePath;ResolutionPresets.StorePath=Path.Combine(root,"preferences.json");var culture=CultureInfo.CurrentCulture;
  try{
   Assert(ResolutionPresets.InputSize(3840,2160,"质量")==new Size(2560,1440),"4K quality");Assert(ResolutionPresets.InputSize(3840,2160,"平衡")==new Size(2259,1271),"4K balanced round");Assert(ResolutionPresets.InputSize(3840,2160,"性能")==new Size(1920,1080),"4K performance");Assert(ResolutionPresets.InputSize(3840,2160,"超级性能")==new Size(1280,720),"4K ultra performance");Assert(ResolutionPresets.InputSize(2560,1440,"性能")==new Size(1280,720)&&ResolutionPresets.InputSize(1920,1080,"超级性能")==new Size(640,360),"Other displays");Assert(ResolutionPresets.InputSize(3440,1440,"质量")==new Size(2293,960),"Ultrawide aspect ratio");Reject(()=>ResolutionPresets.InputSize(0,2160,"质量"),"Invalid output dimensions");Reject(()=>ResolutionPresets.Ratio("bogus"),"Unknown mode rejected");
   CultureInfo.CurrentCulture=new CultureInfo("fr-FR");Assert(StackEngine.ReadIni(ResolutionPresets.BridgeConfig(BridgeIni,"质量"),"amd-nr","Scale")=="0.66666667"&&StackEngine.ReadIni(ResolutionPresets.UpscaleConfig(UpscaleIni,"平衡"),"UpscaleRatio","UpscaleRatioOverrideValue")=="1.7","Invariant config decimals");CultureInfo.CurrentCulture=culture;
   var game=Fixture(root,"bridge");string message=ResolutionPresets.Set(game,"性能","display-A");Assert(!File.Exists(Path.Combine(game.Root,"amd-nr.ini"))&&message.Contains("未安装"),"Saving alone does not install");Assert(ResolutionPresets.Saved(game).Mode=="性能","Per-game preference saved");Install(game,root,BridgeIni,true);string path=Path.Combine(game.Root,"amd-nr.ini");Assert(StackEngine.ReadIni(File.ReadAllText(path),"amd-nr","Scale")=="0.5","Future installation consumes preset");ResolutionPresets.Set(game,"超级性能","display-A");string configured=File.ReadAllText(path);Assert(StackEngine.ReadIni(configured,"amd-nr","Scale")=="0.33333333"&&StackEngine.ReadIni(configured,"Other","Scale")=="0.9"&&StackEngine.ReadIni(configured,"amd-nr","StartOn")=="0"&&StackEngine.ReadIni(configured,"amd-nr","Passes")=="2"&&StackEngine.ReadIni(configured,"amd-nr","Async")=="0","Only scale changes; same-frame and toggle preserved");Assert(StackEngine.Record(game).After["amd-nr.ini"]==Core.Digest(path),"Recovery checksum updated");
   File.WriteAllText(Path.Combine(game.Root,"fixture-component.bin"),"other tool changed it");Reject(()=>ResolutionPresets.Set(game,"质量","display-B"),"Changed component blocks mutation");Assert(File.ReadAllText(path)==configured&&ResolutionPresets.Saved(game).Mode=="超级性能","Rejected mutation preserves INI and preferences");File.WriteAllText(Path.Combine(game.Root,"fixture-component.bin"),"known fixture component");StackEngine.Restore(game);Assert(!File.Exists(path)&&File.Exists(game.Exe)&&ResolutionPresets.Saved(game).Mode=="超级性能","Full restore still works; preference alone retained");
   var other=Fixture(root,"integrated");Install(other,root,UpscaleIni,false);ResolutionPresets.Set(other,"平衡","display-B");string opti=File.ReadAllText(Path.Combine(other.Root,"OptiScaler.ini"));Assert(StackEngine.ReadIni(opti,"UpscaleRatio","UpscaleRatioOverrideEnabled")=="true"&&StackEngine.ReadIni(opti,"UpscaleRatio","UpscaleRatioOverrideValue")=="1.7"&&StackEngine.ReadIni(opti,"QualityOverrides","QualityRatioOverrideEnabled")=="false","Actual global upscale override and exclusivity");Assert(StackEngine.ReadIni(opti,"DlssNr","AmdModelScale")=="0.75"&&StackEngine.ReadIni(opti,"FrameGen","Enabled")=="false","No nested NR scaling or FG changes");Assert(ResolutionPresets.Saved(game).Mode=="超级性能"&&ResolutionPresets.Saved(other).Mode=="平衡","Different games isolated");StackEngine.Restore(other);
   var unknown=Fixture(root,"unsupported");Install(unknown,root,"[Other]\nScale=1\n",false);Reject(()=>ResolutionPresets.Set(unknown,"性能","screen"),"Unknown config schema refused");Assert(ResolutionPresets.Saved(unknown)==null&&File.ReadAllText(Path.Combine(unknown.Root,"OptiScaler.ini"))=="[Other]\nScale=1\n","No fabricated config keys");StackEngine.Restore(unknown);
   var standalone=Fixture(root,"standalone");File.WriteAllText(Path.Combine(standalone.Root,Core.Ini),"[DlssNrOnAmd]\nEnabled=1\n");Core.Save(Core.RecordPath(standalone),new Record{Folder=standalone.Root});Assert(ResolutionPresets.Set(standalone,"质量","screen").Contains("游戏中")&&File.ReadAllText(Path.Combine(standalone.Root,Core.Ini))=="[DlssNrOnAmd]\nEnabled=1\n","Standalone mode is honest manual guidance");File.Delete(Core.RecordPath(standalone));
   string log="raster: back buffer 3840x2160 format 87, network at 1920x1080 (scale 0.50)\n2 asked, 2 accepted\nengine_frame=120 result=1\nengine_frame=240 result=1\n";var evidence=ResolutionLogs.Parse(log);Assert(evidence.OutputWidth==3840&&evidence.InputHeight==1080&&evidence.AcceptedPasses==2&&evidence.FrameSamples==2&&evidence.FailedFrameSamples==0,"RA3 log evidence parsed");var resize=ResolutionLogs.Parse(log+"raster: back buffer 1920x1080 format 87, network at 640x360 (scale 0.33)\nengine_frame=360 result=0\n");Assert(resize.OutputWidth==1920&&resize.InputWidth==640&&resize.FailedFrameSamples==1,"Newest dimensions and failed sampled frame");Assert(ResolutionLogs.Parse("DXGI_ERROR_DEVICE_HUNG").Summary.Contains("异常")&&ResolutionLogs.Parse("").FrameSamples==0,"Errors and empty logs not success");evidence.Source="fixture";Assert(ResolutionLogs.Format(evidence,new PhysicalDisplay{Width=2560,Height=1440},"性能").Contains("游戏输出与所选屏幕不同"),"Windowed mismatch explained");
   var displays=ResolutionPresets.Displays();Assert(displays.All(d=>d.Width>=64&&d.Height>=64),"Physical display dimensions queried");
   using(var form=new MainForm()){form.Show();Application.DoEvents();var button=form.Controls.Find("ResolutionPresetButton",true).Single();Assert(button.Visible&&button.Parent.ClientRectangle.Contains(button.Bounds),"Universal button visible");form.ClientSize=new Size(1004,661);Application.DoEvents();Assert(button.Parent.ClientRectangle.Contains(button.Bounds),"Button at minimum window size");form.Hide();}
   using(var form=new ResolutionForm(game)){form.Show();Application.DoEvents();Assert(form.Controls.Find("ResolutionMode0",true).Length==1&&form.Controls.Find("ResolutionMode3",true).Length==1&&form.Controls.Find("ResolutionApply",true).Single().Visible,"All four modes and apply accessible");var selector=(ComboBox)form.Controls.Find("ResolutionDisplay",true).Single();Assert(selector.SelectedItem!=null&&selector.SelectedItem.ToString().Contains("3840")==displays.Any(d=>d.Device==((PhysicalDisplay)selector.SelectedItem).Device&&d.Width==3840),"Display selector shows detected physical screen");using(var bitmap=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bitmap,new Rectangle(Point.Empty,bitmap.Size));bitmap.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"输入分辨率四档-界面.png"));}form.Hide();}
   Core.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"输入分辨率四档-测试.json"),new{passed=true,checks=checks,displays=displays,scope="Temporary fixtures, actual screen query, four modes, installed configuration, future installation, recovery and log parsing. No real game configuration changed."});
  }finally{CultureInfo.CurrentCulture=culture;ResolutionPresets.StorePath=store;}
 }
}
